name: DL_PSI_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  # - ipykernel # optional -- for interactive development, e.g. Jupyter Notebooks
  # - ipywidgets
  - matplotlib
  - seaborn=0.12.1
  - numpy
  - pandas
  - python-dateutil
  - heyoka.py=0.17.0
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.6
  - pytorch-lightning=1.7.7
  - torchmetrics=0.10.2
  - tensorboard=2.10.1
  - optuna=2.10.1
  - jax=0.4.1 